modLoader = "javafml"
loaderVersion = "[1,)"
license = "GNU GPL v3"

clientSideOnly = true

[[mods]]
modId = "loading_screen_plus"
version = "${version}"
displayName = "Loading Screen Plus"
authors = "Bread_NiceCat"
credits = "shedaniel"
description = '''
A mod to improve the loading screen.
'''
logoFile = "icon.png"

[[dependencies.loading_screen_plus]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.loading_screen_plus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.loading_screen_plus]]
modId = "cloth_config"
mandatory = true
versionRange = "[11.1.106,)"
ordering = "NONE"
side = "BOTH"
